stages:
  prepare:
    cmd: python -m src.preprocess --config configs/train.yaml
    deps:
      - src/preprocess.py
      - configs/train.yaml
      - data/ml-100k/
    outs:
      - data/processed

  train:
    cmd: python -m src.train --config configs/train.yaml
    deps:
      - src/train.py
      - src/engine.py
      - src/model.py
      - configs/train.yaml
      - data/processed/
    outs:
      - artifacts/model

  evaluate:
    cmd: python -m src.evaluate --config configs/train.yaml --model-dir artifacts/model
    deps:
      - src/evaluate.py
      - artifacts/model
      - configs/train.yaml
    metrics:
      - artifacts/metrics/metrics_eval.json
